import Head from "next/head";
import { Inter } from "next/font/google";
import Form from "@/app/comp/Form";
import Data from "@/app/comp/Data";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const route = useRouter()
  return (
    <>
      <Head>
      <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-cyan-500 w-full pb-5 flex-column justify-content-center align-items-center">
        <Form />
        <Data />
      </main>
    </>
  );
}
